# ${plugin.name} Main Configuration
# ${plugin.name} - ${description}

###########################################################################
##                        ENVIRONMENT INFORMATION                        ##
##    This is to make life easier since we have multiple environments    ##
##                                                                       ##
##   Scope: "" (scope [tm/lobby/etc] of servers where                    ##
##              this config is used)                                     ##
##                                                                       ##
##   Production: true (Active on production servers)                     ##
##                                                                       ##
##   Complete: true (if the file is a full configuration.                ##
##                    If false, parent/children configs are needed)      ##
##                                                                       ##
##   Notes: Any special notes about this file                            ##
##          Ex: Children need to define "foo" in order                   ##
##              for the file to be complete.                             ##
##                                                                       ##
###########################################################################

generators:
  - prefix: 2k
    count: 5
    size: 2000
    nether: true
    end: true
    start: 0
    stop: 23
    priority: 1
    days:
      - Sunday
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
      - Saturday
  - prefix: 1k
    count: 5
    size: 1000
    nether: true
    end: true
    start: 0
    stop: 23
    priority: 1
    days:
      - Sunday
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
      - Saturday
  - prefix: 500
    count: 5
    size: 500
    nether: true
    end: true
    start: 0
    stop: 23
    priority: 1
    days:
      - Sunday
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
      - Saturday